### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by Yohn** [zerodytrash/TikTok-Live-Connector#108]
It was working until earlier to, when I started getting the following error message for everyone I try to connect to::

````Error: Request failed with status code 500````

I tried doing it on the example site as well and still get that message.

https://tiktok-chat-reader.zerody.one/

Any chance of finding a work around for this? I've been running it locally so if theres a way to do only on localhost, that would be amazing as well.

Thanks for your hard work on this project. It really has been a dream come true to be able to see who sent gifts and who tapped. I wish tiktok had a way to do this instead of resorting to third party plugin, but since they dont, I've been relying on your project to track the gifters and tappers.

**Comment by Shaionix** [comment]
Same issue here.

**Comment by epicmines33** [comment]
same issue here

**Comment by guilhermedevvv** [comment]
same issue here

**Comment by MrPatryk** [comment]
same here

**Comment by klysmannvieira** [comment]
Same issue here.

**Comment by alanoli** [comment]
Same here

**Comment by alanoli** [comment]
Just tested again, and it worked ... Any thoughts on what was the issue?

**Comment by isaackogan** [comment]
Issue fixed, internal microservice (responsible for the functioning of the sign server) restarted.

Someone asked why the code for the sign server is not public:

The reason we don't just give people the ability to run the sign server is that it generates tokens to TikTok's website to make requests (like making the request to get you the websocket URL). The nature of being able to do this means people can choose to spam TikTok with a massive number of requests and not get any sort of captchas. If they knew our method, they could scrape *any* part of TikTok, not just the LIVE side. TikTok used to block this library because we gave out tokens like that. In the interest of this library running *forever*, we don't give out tokens anymore, only the websocket URL. This means we need the sign API to do all the token stuff behind the scenes so that there are no issues with us getting blocked. Obviously, we can't give out the code to do this, or TikTok will be forced to block it.

Since adopting this method, TikTok have not attempted to block our library for over 6 months now.
At one point they used to block it twice a week. It was absurd.
I understand the inconvenience of it not working in cases like this when I am asleep and not there to fix things that go wrong, but it is much more preferable than no service at all.

Others should have access to restart it when I am asleep, but we recently switched the host running the microservice, and I did not share the details with other library developers.

**Comment by guilhermedevvv** [comment]
> isaackogan

how often does it happen?

**Comment by isaackogan** [comment]
To date, once before

**Comment by klysmannvieira** [comment]
Failed to connect Error: TikTok does not offer a websocket upgrade. Please provide a valid `sessionId` to use request polling instead.

**Comment by Yohn** [comment]
> Issue fixed, an internal microservice (responsible for the functioning of the sign server) had to be restarted. One of the processes behind the sign server crashed and did not restart properly.

Thank you for fixing this, and getting it working again! 
This really is an awesome project, and I'm so glad you and the team have started and continue to maintain it. I was scared in the beginning thinking I would not be able to find a work around to this issue.

**Comment by Yohn** [comment]
This issue is coming up again...

**Comment by isaackogan** [comment]
Fix in-bound, different reason... Being Ddosed.

**Comment by shalevc1098** [comment]
Error: TikTok does not offer a websocket upgrade. Please provide a valid `sessionId` to use request polling instead.
    at WebcastPushConnection.connect (C:\Users\Shalev\Desktop\tiktok\node_modules\tiktok-live-connector\dist\index.js:295:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\Shalev\Desktop\tiktok\src\index.ts:36:21

**Comment by bazz1tv** [comment]
I'm getting this error the past few days now

**Comment by psql** [comment]
hitting the issue again :( any ideas?
