### ISSUE TITLE
Unable to import within default ReactJS App (create-react-app)

### ISSUE THREAD

**Issue by isaackogan** [zerodytrash/TikTok-Live-Connector#22]
Trying to use this package within a React site causes an error:

```
webcastWebsocket.js:26 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at Object../node_modules/tiktok-live-connector/dist/lib/webcastWebsocket.js (webcastWebsocket.js:26:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Object../node_modules/tiktok-live-connector/dist/index.js (index.js:27:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Object../node_modules/tiktok-live-connector/index.js (index.js:1:1)
    at Object.options.factory (react refresh:6:1)
```

This issue suggests it is a circular import: https://stackoverflow.com/questions/37312197/node-js-v6-2-0-class-extends-is-not-a-function-error/ (but I don't think that's the reason)

This is the code for that file:

```
import {Component} from "react";
const { WebcastPushConnection } = require('tiktok-live-connector');

class Test extends Component {

    render() {

        return (
            <div />
        )
    }

}

export default Test;
```

**Comment by isaackogan** [comment]
It seems that for whatever reason, the websocket object (while the correct version) does not have contain a client?

https://cdn.isaackogan.com/vNVCZ

**Comment by isaackogan** [comment]
I would also like to add that _within_ that same directory, creating an index.js file and importing the package works. Just within the React environment does it not work.

**Comment by zerodytrash** [comment]
I think this will not work client-side (in the browser), because TikTok does not support Cross-Origin Resource Sharing (CORS). You would need to disable the same origin policy in the browser (not recommended). And even then, there would still be problems regarding the appending of cookies, etc. All in all, the package is not intended for use on client-side due to browser restrictions. However, it works well in Node environments. You can redirect the data to the client using socket.io or a different websocket framework.

Here is an example project: https://github.com/zerodytrash/TikTok-Chat-Reader

You can also use the public server instance for your website which can handle mutiple connections:

````html
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.4.1/socket.io.min.js"></script>

<script>

    let connection = new io("https://tiktok-chat-reader.zerody.one/");

    connection.emit("setUniqueId", "@username", {
        enableExtendedGiftInfo: true
    })

    connection.on('chat', data => {
        console.log(data)
    })

</script>
````

**Comment by isaackogan** [comment]
Thanks, that makes sense
