### ISSUE TITLE
New free signature provider with more stable and efficient.

### ISSUE THREAD

**Issue by reverse4free** [zerodytrash/TikTok-Live-Connector#63]
Hi, Bro, this is really a great project. But I find that it's default signature provider is not stable and sometimes return an invalid x-bogus as well as _signature result. I'm a reverse engineer who are interested in TikTok including android, iOS and web platform. I have cracked the latest x-bogus and _signature algorithm, and it's working fine for me with your project.

So I want to provide my signature service **FREELY** for this project. I'll generate a permanent free test key of my signature service just for this project. However, I should limit the QPS to 1, to reduce my service cost, hope you could understand D:). This is my [DEMO](https://github.com/reverse4free/TiktokPerseusWeb) project forked from TikTok-Live-Connector, I just replace the signature provider with ours. 

If you are interested in my suggestion, please contact me. And I am happy to pull a merge request with my signature provider, thanks.

**Comment by zerodytrash** [comment]
hi,

This library currently already has the ability to set a custom signature provider.
You just have to adjust the path and param names on your server to make it work. (from `get_web_sign` to `webcast/sign_url`, etc...).

```javascript
const { WebcastPushConnection, signatureProvider } = require('tiktok-live-connector');

signatureProvider.config.signProviderHost = "https://new-sign-tt-aycoaohohf.us-west-1.fcapp.run/";
signatureProvider.config.extraParams["key"] = "<apikey>";

// Connect as usual...
```

So users can set your signature provider if they prefer. In the next update I can also implement an option to set the `providerPath` via config.

The fact that the Signature Server used by default sometimes returns invalid signatures is an intentional behavior. It occurs when the client either makes too many requests or the request comes from China. Yes, we block requests from China. Bytedance keeps an eye on our projects :)

**Comment by reverse4free** [comment]
Thanks, Bro. To show my respect for you and your great project, I decide to donate a permanent free test key for guys who are interested in your project. The key is "ecTtktP7XJtz5OCTxMRqn9MR34ilh9GSGrq+eryJu6LDXob6pbaVyj8=", have fun!

In addition, hope to cooperate with you to do more geek projects in the future D:).

Bring my best wishes to you.
